# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: catalog.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'catalog.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcatalog.proto\x12\x07\x63\x61talog\"-\n\x0cStockRequest\x12\x0b\n\x03sku\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"c\n\rStockResponse\x12\x0b\n\x03sku\x18\x01 \x01(\t\x12\x14\n\x0cproduct_name\x18\x02 \x01(\t\x12\r\n\x05stock\x18\x03 \x01(\x05\x12\r\n\x05price\x18\x04 \x01(\x01\x12\x11\n\tavailable\x18\x05 \x01(\x08\x32\x46\n\x07\x43\x61talog\x12;\n\nCheckStock\x12\x15.catalog.StockRequest\x1a\x16.catalog.StockResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'catalog_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STOCKREQUEST']._serialized_start=26
  _globals['_STOCKREQUEST']._serialized_end=71
  _globals['_STOCKRESPONSE']._serialized_start=73
  _globals['_STOCKRESPONSE']._serialized_end=172
  _globals['_CATALOG']._serialized_start=174
  _globals['_CATALOG']._serialized_end=244
# @@protoc_insertion_point(module_scope)
